### ISSUE TITLE
请问neno中设置的库和tg中/repo后设置的是同一个吗？

### ISSUE THREAD

**Issue by taklele** [openneno/neno-tg#1]
程序和tgbot都可以正常运行，但是数据却没有同步。
配置
<img width="258" alt="1" src="https://user-images.githubusercontent.com/2526519/153886049-f06b2dcf-ea36-4df6-b781-62eb16e6a1db.png">
<img width="209" alt="2" src="https://user-images.githubusercontent.com/2526519/153886123-87008b04-bf54-4170-bb18-cba84c266126.png">

数据
<img width="531" alt="3" src="https://user-images.githubusercontent.com/2526519/153886137-a2e95370-da2e-4e8a-b61f-d899f05ccbba.png">
最终显示
<img width="99" alt="5" src="https://user-images.githubusercontent.com/2526519/153886174-ae89eda4-0813-4841-aa18-691caa4881e6.png">

页面中不显示我在tgbot中提交的“是大法是大法”，请问是哪里配置不对么？

**Comment by Mran** [comment]
已修复，是客户端的问题。
https://github.com/openneno/neno/commit/32c1b41963501edf54b9259e7a25f34158293a87
